// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWqyFRV-SudQ5cgm7WqrMfDp5_8jdJ3RI',
    appId: '1:343352954397:web:357b3fab88cb1eb4a680f4',
    messagingSenderId: '343352954397',
    projectId: 'field-monitoring-124ad',
    authDomain: 'field-monitoring-124ad.firebaseapp.com',
    storageBucket: 'field-monitoring-124ad.appspot.com',
    measurementId: 'G-ZV1HXVEY87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJGGFYS5wBnVvlj93bhGJelzQRyx2nOcs',
    appId: '1:343352954397:android:75b2216fc227b6e3a680f4',
    messagingSenderId: '343352954397',
    projectId: 'field-monitoring-124ad',
    storageBucket: 'field-monitoring-124ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRTj91M2SZrOD_gn0_cbFSOQKkHcjiCak',
    appId: '1:343352954397:ios:845def0c11e49cb2a680f4',
    messagingSenderId: '343352954397',
    projectId: 'field-monitoring-124ad',
    storageBucket: 'field-monitoring-124ad.appspot.com',
    iosClientId: '343352954397-gfco8s07ls1qvmijfc3kgdj2e1li4sc3.apps.googleusercontent.com',
    iosBundleId: 'gahezit.com.example.orbitsapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRTj91M2SZrOD_gn0_cbFSOQKkHcjiCak',
    appId: '1:343352954397:ios:e079830a6803ce0fa680f4',
    messagingSenderId: '343352954397',
    projectId: 'field-monitoring-124ad',
    storageBucket: 'field-monitoring-124ad.appspot.com',
    iosClientId: '343352954397-gfgigi0qqgfl5r8lduiecar7er1ouocf.apps.googleusercontent.com',
    iosBundleId: 'com.iotecksolutions.flutterField_MonitoringOrbits',
  );
}
